"""classification

Revision ID: 6ccaafbacb8e
Revises: bf5b29b4d9cb
Create Date: 2026-09-02 09:59:24.086584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccaafbacb8e'
down_revision: Union[str, Sequence[str], None] = 'bf5b29b4d9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULLTIME', 'PARTTIME', 'CONTRACTOR', 'INTER', name='employmenttype'), nullable=False),
    sa.Column('grade', sa.Enum('JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', 'PRINCIPAL', name='grade'), nullable=False),
    sa.Column('is_exempt', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_created_at'), 'classifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_classifications_effective_from'), 'classifications', ['effective_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_effective_from'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_created_at'), table_name='classifications')
    op.drop_table('classifications')
    # ### end Alembic commands ###
