"""compiliancerecord

Revision ID: 9d99fa322013
Revises: 6ccaafbacb8e
Create Date: 2026-09-03 08:12:00.491173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d99fa322013'
down_revision: Union[str, Sequence[str], None] = '6ccaafbacb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiliancerecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('NDA', 'BACKGROUNDCHECK', 'CERTIFICATION', 'VISA', name='recordtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'EXPIRED', name='status'), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('expires_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compiliancerecords_created_at'), 'compiliancerecords', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compiliancerecords_created_at'), table_name='compiliancerecords')
    op.drop_table('compiliancerecords')
    # ### end Alembic commands ###
