"""empty message

Revision ID: bf5b29b4d9cb
Revises: e93a6362be25
Create Date: 2026-09-02 08:45:32.843014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5b29b4d9cb'
down_revision: Union[str, Sequence[str], None] = 'e93a6362be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employments_person_id_key'), 'employments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('employments_person_id_key'), 'employments', ['person_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
