"""unique - employment

Revision ID: e93a6362be25
Revises: a617b7a230c6
Create Date: 2026-09-02 08:24:57.743111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93a6362be25'
down_revision: Union[str, Sequence[str], None] = 'a617b7a230c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employments', ['person_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employments', type_='unique')
    # ### end Alembic commands ###
